context:
  version: 3.0.0
  python_min: "3.10"

package:
  name: deeplabcut
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/deeplabcut/deeplabcut-${{ version }}.tar.gz
  sha256: 66eb56d0634460bf9e4dc7e87f4f52d920b3ffe4dadd65ed07b5d025e630c3b8
  # patches:
  # Le's try and either fix these in the codebase/ensure they are truly necessary
  # The qtpy ones are likely relevant still; others like multi animal export need review.
    # - patches/0001-Do-not-install-download-script.patch
    # - patches/0002-Silence-warnings-about-DLC-lite-mode.patch
    # - patches/0003-Do-not-modify-tensorflow-warnings.patch
    # - patches/0004-Silence-warnings-about-missing-pytorch.patch
    # - patches/0005-Use-qtpy-instead-of-PySide6.patch
    # - patches/0006-Remove-hard-dependency-on-torch.patch
    # - patches/0007-Lazy-Import-pyqt-and-default-to-PySide6.patch
    # - patches/0008-add-outputs-for-multi-animal-model-export.patch
    # - patches/0009-Loosen-dependencies.patch

build:
  # Confirm with upstream before making this entry point
  # https://github.com/DeepLabCut/DeepLabCut/pull/1547
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - dlc = deeplabcut.__main__:main

requirements:
  host:
    - python  ${{ python_min }}.*
    - pip
    - setuptools >=61
  run:
    - python >=${{ python_min }}
    - albumentations <=1.4.3
    - dlclibrary >=0.0.12
    - einops
    - filelock >=3.12,<3.16
    - filterpy >=1.4.4
    - huggingface_hub >=0.23
    - imageio-ffmpeg
    - imgaug >=0.4
    - matplotlib-base >=3.3,<3.9,!=3.7,!=3.7.1
    - networkx >=2.6
    - numba >=0.54
    - numpy >=1.18.5,<2
    - opencv
    - packaging >=26
    - pandas >=2.2,<3
    - pillow >=7.1
    - pycocotools
    - pydantic >=2,<3
    - pytables >3.8
    - pytorch >=2
    - pyyaml
    - ruamel.yaml >=0.15
    - scikit-image >=0.17
    - scikit-learn >=1
    - scipy >=1.9
    - statsmodels >=0.11
    - timm
    - torchvision
    - tqdm
  run_constraints:
    # GUI
    - napari-deeplabcut >=0.3.1
    - qdarkstyle ==3.1
    # TensorFlow extras are optional
    - protobuf <7
    - tensorflow >=2.12
    - tensorpack >=0.11
    - tf-keras
    - tf_slim >=1.1


tests:
  - script:
      - pip check
      - python -c "import deeplabcut"
    requirements:
      run:
        - pip
        - python ${{ python_min }}.*
        - "opencv * headless*"

about:
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: DeepLabCut is a toolbox for markerless pose estimation of animals performing various tasks.
  homepage: https://www.deeplabcut.org
  repository: https://github.com/DeepLabCut/DeepLabCut

extra:
  recipe-maintainers:
    - hmaarrfk
    - C-Achard
    - deruyter92
